AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  environmentName:
    Type: String
    Description: The name of the environment to be deployed
  BucketName:
    Type: String
    Description: The name of the S3 bucket where the Lambda function code is stored
  CodeS3Key:
    Type: String
    Description: The key of the S3 object containing the Lambda function code
  LambdaVersion:
    Type: String
    Description: The version of the Lambda function code
Resources:
  ApiGatewayCloudWatchRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
  ApiGatewayAccount:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn: !GetAtt ApiGatewayCloudWatchRole.Arn
  dynnamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: car
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
  lamdaRoleToAccessDynammoDB:
    Type: AWS::IAM::Role
    Properties:
      RoleName: lambda-dynamodb-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: lambda-dynamodb-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Scan
                Resource: !GetAtt dynnamoDBTable.Arn
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "arn:aws:logs:*:*:*"
  carCreateLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "car-create-function-${LambdaVersion}"
      Handler: createCar.handler
      Role: !GetAtt lamdaRoleToAccessDynammoDB.Arn
      Runtime: nodejs20.x
      Code: 
        S3Bucket: !Ref BucketName
        S3Key: !Ref CodeS3Key
      Architectures:
        - x86_64
  carListLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "car-list-function-${LambdaVersion}"
      Handler: listCars.handler
      Role: !GetAtt lamdaRoleToAccessDynammoDB.Arn
      Runtime: nodejs20.x
      Code: 
        S3Bucket: !Ref BucketName
        S3Key: !Ref CodeS3Key
      Architectures:
        - x86_64
  carApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: CarAPI
  carApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt carApiGateway.RootResourceId
      PathPart: cars
      RestApiId: !Ref carApiGateway
  carCreateMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref carApiGateway
      ResourceId: !Ref carApiResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${carCreateLambdaFunction.Arn}/invocations
  carListMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref carApiGateway
      ResourceId: !Ref carApiResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${carListLambdaFunction.Arn}/invocations
  createCarLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref carCreateLambdaFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${carApiGateway}/*/POST/cars
  listCarLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref carListLambdaFunction
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${carApiGateway}/*/GET/cars
  carApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - carCreateMethod
      - carListMethod
    Properties:
      RestApiId: !Ref carApiGateway
  carApiStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      StageName: !Ref environmentName
      RestApiId: !Ref carApiGateway
      DeploymentId: !Ref carApiDeployment
      MethodSettings:
        - ResourcePath: "/*"
          HttpMethod: "*"
          LoggingLevel: INFO
          DataTraceEnabled: true
          MetricsEnabled: true
Outputs:
  ApiListEndpoint:
    Description: "API Gateway endpoint URL for the Car API - The list GET method can be accessed at this URL"
    Value: !Sub "https://${carApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${environmentName}/cars"
  ApiCreateEndpoint:
    Description: "API Gateway endpoint URL for the Car API - The create POST method can be accessed at this URL"
    Value: !Sub "https://${carApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${environmentName}/cars"
